=== dita-community/org.dita-community.i18n/plugin/conf/grouping-and-sorting/grouping_and_sorting_rules.dtd
<!--=============================================================
    Back-of-the-Book Index Configuration and Sorting Rules
    Specification document.

    The namespace URI for this XML vocabulary is:
    
    http://www.innodata-isogen.com/vocabularies/i18n_support/grouping_and_sorting_config
    
    Adapted to the DITA Community org.dita-community.i18n project by Eliot Kimber for 
    use with the DITA Open Toolkit.
    
    Generalized to grouping and sorting generally, not just indexing.
    
    Copyright (c) 2016 DITA Community Project (dita-commmunity.org)
    
    Original copyright:

    Copyright (c) 2003, 2004 Innodata Isogen


    This DTD defines documents that configure back-of-the-book
    index generation for different national languages.

    For a given national language index you need the following information:

    - The collation sequence for the characters in the language
    - The headings for the index sections (e.g., "A", "B", "C" in
      English)
    - The mapping of characters in the language to specific headings.
      For example, several different characters might all sort
      under "C" in a particular language.
    - For each sort grouping, the sort order within that grouping.
    
    [Revision History]
    2013-11-01 Antenna House, Inc. Toshihiko Makita
    - Add ignore_english to sort_method content model.
       <!ELEMENT sort_method
         ((sort_by_members |
           sort_between_keys)?,
          (sort_english_before |
           sort_english_after)?,
           ignore_english?)
        >
        
    2011-11-21 Antenna House, Inc. Toshihiko Makita
    - Change index_config content model to allow multiple language-code to 
      hold dialects.
      The parent language code must be written as the *FIRST* national_language
      element contents.
      <!ELEMENT index_config
                (national_language, ==> national_language+
                 description,
                 collation_spec,
                 sort_method,
                 group_definitions)
      >

    =============================================================-->

<!ELEMENT grouping_and_sorting_rules
  (metadata,
   index_config+)
>
<!ATTLIST grouping_and_sorting_rules
  xmlns
    CDATA
    #FIXED "http://www.innodata-isogen.com/vocabularies/i18n_support/grouping_and_sorting_config"
>    

<!ELEMENT metadata
  (title?,
   description?,
   copyright?,
   security?,
   revision_history?)
>

<!-- Descriptive title of the database, e.g. "Foo doctype index configuration"
  -->
<!ELEMENT title
  (#PCDATA)
>

<!-- A generic description -->
<!ELEMENT description
  (p+)
>

<!ELEMENT p
  (#PCDATA)
>


<!-- Contains a copyright statement for the configuration document
  -->
<!ELEMENT copyright
  (p+)
>

<!-- Contains a security statement for the configuration document,
     e.g., "For Internal Use Only" or some such.
  -->
<!ELEMENT security
  (p+)
>

<!-- Revision history is intended to capture the development history
     of the configuration document itself.
  -->
<!ELEMENT revision_history
  (revision*)
>

<!-- The revision element describes a single revision to the configuration document.
  -->
<!ELEMENT revision
  (date,
   author,
   description)
>

<!-- Contains the date the revision was made.
  -->
<!ELEMENT date
  (#PCDATA)
>

<!-- The author of the revision -->
<!ELEMENT author
  (#PCDATA)
>

<!--
     Defines the index configuration for a single
     national language.

  -->
<!ELEMENT index_config
  (national_language+,
   description,
   collation_spec,
   sort_method,
   group_definitions)
>

<!ELEMENT sort_method
  ((sort_by_members |
    sort_between_keys)?,
   (sort_english_before |
    sort_english_after)?,
    ignore_english?)
>

<!-- Indicates that the grouping method is to sort by the explicit
     group membership. This is the default grouping strategy.
  -->
<!ELEMENT sort_by_members
  EMPTY
>

<!-- Indicates that the grouping method is to sort between the
     index group keys rather than by the explicit group membership.
  -->
<!ELEMENT sort_between_keys
  EMPTY
>

<!-- Indicates that English terms should be sorted before the main
     language's entries. This is the default.
  -->
<!ELEMENT sort_english_before
  EMPTY
>

<!-- Indicates that English terms should be sorted after the main
     language's entries.
  -->
<!ELEMENT sort_english_after
  EMPTY
>

<!-- Indicates that English group key should not be adopted
     if no entry matches fo this group definition.
  -->
<!ELEMENT ignore_english
  EMPTY
>



<!-- Contains the language code for the national language
     this index configuration applies to.

     Language code is as for xml:lang.
  -->
<!ELEMENT national_language
  (#PCDATA)
>

<!-- Added. 2006/05/23 t.makita
     "use_java_collator" specifies whether to use Java standard collator 
     or ICU collator.
  -->

<!ELEMENT use_java_collator
  EMPTY
>

<!-- Added. 2006/05/23 t.makita
     "replace_rules" specifies wheter to use collation sequence directly 
     or adding standard collator rules.
  -->
<!ELEMENT replace_rules
  EMPTY
>

<!-- Contains the specification of the collation sequence to use
     for the language. If no explicit collation specification is
     provided, the implementing system's built-in collation rules
     for the national language are used.
  -->
<!--ELEMENT collation_spec
  (java_collation_spec?)
-->
<!ELEMENT collation_spec
  (use_java_collator? , replace_rules? , java_collation_spec?)
>


<!-- Contains a Java RuleBasedCollator
     (http://java.sun.com/products/jdk/1.2/docs/api/java/text/RuleBasedCollator.html)

     rule set.
  -->
<!ELEMENT java_collation_spec
  (#PCDATA |
   include_collation_spec)*
>

<!-- Specifes the name of the collation specification file to use. This file
     must contain a Java collation spec as used with the RuleBasedCollator
     class.

     The value is interpreted as a Java resource filename resolved relative to the
     class path. Normally this would be relative to the "dtds\" directory, which
     must already be in the classpath for other reasons.

     If more than one include_collation_spec is specified, then all the rule sets
     are used for the collator.

     If include_collation_spec is used, any other text content within java_collation_spec
     is ignored. That is, the intended content model is (#PCDATA | include_collation_spec+).
  -->
<!ELEMENT include_collation_spec
  (#PCDATA)
>

<!-- Defines the groupings used to organize the index entries -->
<!ELEMENT group_definitions
  (term_group+)
>

<!-- Defines a single index term group -->
<!ELEMENT term_group
  (group_key,
   group_label?,
   group_sort_key?,
   group_members)
>

<!-- The key used in organizing index entries into their proper groups.
     This is the value used, for example, for the top-level xsl:key
     use= string.

     If group_label is not also specified, then the group_key is also
     used as the group label.

     Use group_sort_key if the group key will not sort the group
     into the right position.

  -->
<!ELEMENT group_key
  (#PCDATA)
>

<!-- The text to be displayed for the index group in the composed index.

     The group label is optional. If not specified, the group key is also
     used as the group label.
  -->
<!ELEMENT group_label
  (#PCDATA)
>

<!-- The key used to determine the collation order of the group if it is
     different from the collation order of the group label.
  -->
<!ELEMENT group_sort_key
  (#PCDATA)
>

<!-- Specifies the characters that make up this index group. Must include
     all case varriants e.g.:

     <group_members><char_or_seq>a</char_or_seq><char_or_seq>A</char_or_seq>
     </group.members>

     The last_member specifies the character that is the last member of the
     last group in the index configuration. This is for languages that use
     the "sort_between_keys" method of group definition so that the system
     can distinguish characters that are outside the range of the last
     index group.
  -->
<!ELEMENT group_members
  (char_or_seq* |
   last_member)
>

<!-- Specifies either a single character or a sequence of characters that
     are treated as a single character for the purpose of determining
     grouping and sorting within the group.
  -->
<!ELEMENT char_or_seq
  (#PCDATA)
>

<!ELEMENT last_member
  (char_or_seq)
>

=== dita-community/org.dita-community.i18n/plugin/conf/grouping-and-sorting/grouping_and_sorting_rules.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE grouping_and_sorting_rules SYSTEM "grouping_and_sorting_rules.dtd" [
<!ENTITY ar SYSTEM "ar/ar.xml">
<!ENTITY bg SYSTEM "bg/bg.xml">
<!ENTITY ca SYSTEM "ca/ca.xml">
<!ENTITY cs SYSTEM "cs/cs.xml">
<!ENTITY da SYSTEM "da/da.xml">
<!ENTITY de SYSTEM "de/de.xml">
<!ENTITY el SYSTEM "el/el.xml">
<!ENTITY en SYSTEM "en/en.xml">
<!ENTITY es SYSTEM "es/es.xml">
<!ENTITY et SYSTEM "et/et.xml">
<!ENTITY fa SYSTEM "fa/fa.xml">
<!ENTITY fi SYSTEM "fi/fi.xml">
<!ENTITY fr SYSTEM "fr/fr.xml">
<!ENTITY he SYSTEM "he/he.xml">
<!ENTITY hi SYSTEM "hi/hi.xml">
<!ENTITY hr SYSTEM "hr/hr.xml">
<!ENTITY hu SYSTEM "hu/hu.xml">
<!ENTITY id SYSTEM "id/id.xml">
<!ENTITY is SYSTEM "is/is.xml">
<!ENTITY it SYSTEM "it/it.xml">
<!ENTITY ja SYSTEM "ja/ja.xml">
<!ENTITY kk SYSTEM "kk/kk.xml">
<!ENTITY km SYSTEM "km/km.xml">
<!ENTITY kn SYSTEM "kn/kn.xml">
<!ENTITY ko SYSTEM "ko/ko.xml">
<!ENTITY lo SYSTEM "lo/lo.xml">
<!ENTITY lv SYSTEM "lv/lv.xml">
<!ENTITY lt_ic SYSTEM "lt/lt.xml">
<!ENTITY ms SYSTEM "ms/ms.xml">
<!ENTITY my SYSTEM "my/my.xml">
<!ENTITY nl SYSTEM "nl/nl.xml">
<!ENTITY no SYSTEM "no/no.xml">
<!ENTITY pl SYSTEM "pl/pl.xml">
<!ENTITY pt SYSTEM "pt/pt.xml">
<!ENTITY ro SYSTEM "ro/ro.xml">
<!ENTITY ru SYSTEM "ru/ru.xml">
<!ENTITY sk SYSTEM "sk/sk.xml">
<!ENTITY si SYSTEM "si/si.xml">
<!ENTITY sl SYSTEM "sl/sl.xml">
<!ENTITY sv SYSTEM "sv/sv.xml">
<!ENTITY sw SYSTEM "sw/sw.xml">
<!ENTITY ta SYSTEM "ta/ta.xml">
<!ENTITY te SYSTEM "te/te.xml">
<!ENTITY tl SYSTEM "tl/tl.xml">
<!ENTITY th SYSTEM "th/th.xml">
<!ENTITY tr SYSTEM "tr/tr.xml">
<!ENTITY uk SYSTEM "uk/uk.xml">
<!ENTITY vi SYSTEM "vi/vi.xml">
<!ENTITY zh-CN SYSTEM "zh-CN/zh-CN.xml">
<!ENTITY zh-TW SYSTEM "zh-TW/zh-TW.xml">
]>
<grouping_and_sorting_rules xmlns="http://www.innodata-isogen.com/vocabularies/i18n_support/grouping_and_sorting_config">
    <metadata>
        <title>Sample Back-of-the-Book Index Rules</title>
        <description>
            <p>Demonstrates how to configure an internationalized index.</p>
        </description>
        <copyright>
            <p>Copyright (C) 2003, 2004 Innodata Isogen</p>
            <p>This sample may be used to create derivative text databases without restriction.</p>
        </copyright>
        <security>
            <p>For Public Use</p>
        </security>
        <revision_history>
            <revision>
                <date>2016-01-07</date>
                <author>Toshihiko Makita, Antenna House, Inc.</author>
                <description>
                    <p>Correct Ukrainian (uk) index configuration</p>
                    <p>Correct the "Y" position &amp; comment of Latvian.</p>
                </description>
            </revision>
            <revision>
                <date>2015-10-10</date>
                <author>Toshihiko Makita, Antenna House, Inc.</author>
                <description>
                    <p>Add (modify) xx-sort-rules.txt to sort Latin characters before non-Latin characters for DITA-OT 2.x.</p>
                    <p>- Arabic (ar)</p>
                    <p>- Bulgarian (bg)</p>
                    <p>- Greek (el)</p>
                    <p>- Persian (fa)</p>
                    <p>- Hebrew (he)</p>
                    <p>- Hindi (hi)</p>
                    <p>- Korean (ko): Also changed collator from Java to ICU.</p>
                    <p>- Kazakh (kk)</p>
                    <p>- Khmer (km)</p>
                    <p>- Kannada (kn)</p>
                    <p>- Myanmar (my)</p>
                    <p>- Russian (ru)</p>
                    <p>- Sinhala (si)</p>
                    <p>- Telugu (te)</p>
                    <p>- Thai (th)</p>
                </description>
            </revision>
            <revision>
                <date>2015-10-07</date>
                <author>Toshihiko Makita, Antenna House, Inc.</author>
                <description>
                    <p>Add Myanmar index configuration (my)</p>
                    <p>Add Hindi index configuration (hi)</p>
                    <p>Add Telugu index configuration (te)</p>
                    <p>Add Tamil index configuration (ta)</p>
                    <p>Add Kannada index configuration (kn)</p>
                    <p>Add Lao index configuration (lo)</p>
                    <p>Add Persian index configuration (fa)</p>
                    <p>Fix th bug: group_members/lastmember was not defined.</p>
                </description>
            </revision>
            <revision>
                <date>2015-03-26</date>
                <author>Toshihiko Makita, Antenna House, Inc.</author>
                <description>
                    <p>Fix Estonian index configuration. (et)</p>
                    <p>- Add "et-sort-rules.txt" to collation spec. Set primary difference between "v" nad "w".</p>
                    <p>  This is probably the ICU's collation definition mistake.</p>
                </description>
            </revision>
            <revision>
                <date>2014-12-20</date>
                <author>Toshihiko Makita, Antenna House, Inc.</author>
                <description>
                    <p>Fix Dutch index configuration. (nl)</p>
                    <p>- Add "Ä" to "A" entry.</p>
                    <p>Fix Romanian index configuration. (ro)</p>
                    <p>- Add U+0218, U+0219 to "Ş" entry.</p>
                    <p>- Add U+021A, U+021B to "Ţ" entry.</p>
                </description>
            </revision>
            <revision>
                <date>2014-08-20</date>
                <author>Toshihiko Makita, Antenna House, Inc.</author>
                <description>
                    <p>Refine Latvian index configuration. (lv)</p>
                    <p>- Set primary difference between following characters by introducing lv-sort-rules.txt.</p>
                    <p>  "A" and "Ā", "E" and "Ē", "I" and "Ī", "U" and "Ū"</p>
                    <p>Refine Lithuanian index configuration. (lt)</p>
                    <p>- Set primary difference between following characters by introducing lt-sort-rules.txt.</p>
                    <p>  "A" and "Ą", "E" and "Ę" and "Ė", "I" and "Į" and "Y", "U" and "Ų" and "Ū"</p>
                </description>
            </revision>
            <revision>
                <date>2014-04-27</date>
                <author>Toshihiko Makita, Antenna House, Inc.</author>
                <description>
                    <p>Refine Croatian index configuration. (hr)</p>
                    <p>- Add language code "hr-HR".</p>
                    <p>- Add "Dž" to "DŽ" entry.</p>
                    <p>- Add "Lj" to "LJ" entry.</p>
                    <p>- Add "Nj" to "NJ" entry.</p>
                    <p>Refine Estonian index configuration. (et)</p>
                    <p>- Change the alphabet order based on http://en.wikipedia.org/wiki/Estonian_alphabet</p>
                    <p>Refine Icelandic index configuration. (is)</p>
                    <p>- Add language code "is-IS".</p>
                    <p>Refine Latvian index configuration. (lv)</p>
                    <p>- Rename la.xml to lv.xml.</p>
                    <p>- Add language code "lv-LV"</p>
                    <p>Modify Lithuanian index configuration. (lt)</p>
                    <p>- Add language code "lt-LT"</p>
                    <p>- Add index group "Ą","Ę","Ė","Į","Ų","Ū".</p>
                    <p>Refine Slovenian index configuration. (sl)</p>
                    <p>- Add language code "sl-SI"</p>
                </description>
            </revision>
            <revision>
                <date>2014-04-26</date>
                <author>Toshihiko Makita, Antenna House, Inc.</author>
                <description>
                    <p>Add Tagalog index configuration for testing. (tl)</p>
                    <p>- Tagalog is used in Philippines.</p>
                    <p>Add Sinhala index configuration for testing. (si)</p>
                    <p>- Sinhala is used in  Sri Lanka.</p>
                    <p>Add Khmer index configuration for testing. (km)</p>
                    <p>- Khmer is used in  Cambodia.</p>
                    <p>Add Swahili index configuration for testing. (sw)</p>
                </description>
            </revision>
            <revision>
                <date>2014-04-15</date>
                <author>Toshihiko Makita, Antenna House, Inc.</author>
                <description>
                    <p>Add Kazakh index configuration for testing. (kk)</p>
                </description>
            </revision>
            <revision>
                <date>2013-12-31</date>
                <author>Toshihiko Makita, Antenna House, Inc.</author>
                <description>
                    <p>Change Thai last character from ໝ U+0EDD to ฮ U+0E2E.</p>
                    <p>U+0EDD is illegal for Thai because it belongs to Lao.</p>
                </description>
            </revision>
            <revision>
                <date>2013-12-27</date>
                <author>Toshihiko Makita, Antenna House, Inc.</author>
                <description>
                    <p>- Add "ms" entry.</p>
                    <p>- Change to use entity reference for each language.</p>
                </description>
            </revision>
            <revision>
                <date>2013-12-25</date>
                <author>Shinyu Murakami, Antenna House, Inc. (Toshihiko Makita, Antenna House, Inc)</author>
                <description>
                    <p>Modify "id" entry.</p>
                    <p>- Remove (comment out) java_collation_spec and uncertain entry members.</p>
                    <p>Add "vi-VN"</p>
                </description>
            </revision>
            <revision>
                <date>2013-11-01</date>
                <author>Toshihiko Makita, Antenna House, Inc.</author>
                <description>
                    <p>Modify "bg","ru" entry.</p>
